shared:
    image: node:6

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - prep: npm install screwdriver-template-main
            - template: screwdriver/template-publish
