shared:
    image: node:6

jobs:
    publisher:
        requires: [~pr, ~commit]
        steps:
            - prep: npm install screwdriver-template-main
            - template: node ./node_modules/.bin/template-publish
        environment:
              SD_TEMPLATE_PATH: './sd-template-anaconda3.yaml'
